version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "ci/cd"
      - "github-actions"
    ignore:
      - dependency-name: "actions/checkout"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
    assignees:
      - "stayhydated"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
    assignees:
      - "stayhydated"
