edition = "2024"                  # Keep in sync with Cargo.toml.
force_explicit_abi = false
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
# ignore = ["tests-paths"]
