[formatting]
align_entries = false
column_width = 100
compact_arrays = false
reorder_inline_tables = true
reorder_keys = true

[[rule]]
include = [ "**/Cargo.toml" ]
keys = [ "package" ]

[rule.formatting]
align_entries = false
reorder_keys = false
